import puppeteer from "puppeteer-core";

const browser = await puppeteer.launch({ headless: true, executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", args: ["--no-sandbox"] });
const page = await browser.newPage();
const pause = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
const clickButton = async (label) => page.evaluate((text) => {
  const button = [...document.querySelectorAll("button")].find((node) => node.textContent?.trim() === text && node.getBoundingClientRect().width > 0);
  if (!(button instanceof HTMLElement)) throw new Error(`找不到按钮：${text}`);
  button.click();
}, label);
const clickButtonContaining = async (label) => page.evaluate((text) => {
  const button = [...document.querySelectorAll("button")].find((node) => node.textContent?.includes(text) && node.getBoundingClientRect().width > 0);
  if (!(button instanceof HTMLElement)) throw new Error(`找不到按钮：${text}`);
  button.click();
}, label);
const waitForImages = async () => page.evaluate(() => Promise.all([...document.images].map((image) => image.complete ? image.decode().catch(() => undefined) : new Promise((resolve) => { image.addEventListener("load", resolve, { once: true }); image.addEventListener("error", resolve, { once: true }); }))));
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
page.on("console", (message) => { if (message.type() === "error") console.error(message.text()); });
await page.goto(process.env.QA_URL ?? "http://127.0.0.1:3000", { waitUntil: "networkidle0" });
await page.type('input[name="username"]', "admin");
await page.type('input[name="password"]', "999999");
await page.click("form button");
await page.waitForSelector('button[aria-label="打开菜单"]');
await pause(700);
await page.screenshot({ path: "/tmp/ihealth-home.png", fullPage: true });
await page.click('button[aria-label="打开菜单"]');
await page.waitForFunction(() => [...document.querySelectorAll("button")].some((node) => node.textContent?.trim() === "食物" && node.getBoundingClientRect().width > 0));
await clickButton("食物");
await page.waitForFunction(() => document.body.textContent?.includes("种营养关系"));
await pause(700);
await page.screenshot({ path: "/tmp/ihealth-foods.png", fullPage: true });
await page.click('button[aria-label="选择食物分类"]');
await page.waitForSelector('[role="dialog"]');
await pause(300);
await page.screenshot({ path: "/tmp/ihealth-food-categories.png" });
await clickButton("关闭");
await page.evaluate(() => { const heading = [...document.querySelectorAll("h2")].find((node) => node.textContent?.trim() === "三文鱼"); const button = heading?.closest("button"); if (button instanceof HTMLElement) button.click(); });
await page.waitForFunction(() => document.body.textContent?.includes("三文鱼含有哪些营养成分？"));
await waitForImages();
await page.screenshot({ path: "/tmp/ihealth-salmon.png", fullPage: true });
await page.click('button[aria-label="返回"]');
const menuButton = await page.waitForSelector('button[aria-label="打开菜单"]');
await menuButton.click();
await page.waitForFunction(() => [...document.querySelectorAll("button")].some((node) => node.textContent?.trim() === "营养素" && node.getBoundingClientRect().width > 0));
await clickButton("营养素");
await page.waitForFunction(() => [...document.querySelectorAll("button")].some((node) => node.textContent?.includes("维生素 C") && node.getBoundingClientRect().width > 0));
await page.evaluate(() => { const button = [...document.querySelectorAll("button")].find((node) => node.textContent?.includes("维生素 C") && node.getBoundingClientRect().width > 0); if (button instanceof HTMLElement) button.click(); });
await page.waitForFunction(() => document.body.textContent?.includes("你想了解什么？"));
await waitForImages();
await pause(700);
await page.screenshot({ path: "/tmp/ihealth-vitamin-c.png", fullPage: true });
await clickButtonContaining("维生素 C 有什么作用？");
await pause(500);
await page.screenshot({ path: "/tmp/ihealth-vitamin-c-effects.png", fullPage: true });
await page.click('button[aria-label="返回"]');
await page.click('button[aria-label="返回"]');
await page.click('button[aria-label="打开菜单"]');
await clickButton("补充剂");
await page.waitForFunction(() => [...document.querySelectorAll("button")].some((node) => node.textContent?.includes("鱼油") && node.getBoundingClientRect().width > 0));
await page.evaluate(() => { const button = [...document.querySelectorAll("button")].find((node) => node.textContent?.includes("鱼油") && node.getBoundingClientRect().width > 0); if (button instanceof HTMLElement) button.click(); });
await page.waitForFunction(() => document.body.textContent?.includes("如何选择鱼油？"));
await waitForImages();
await pause(500);
await page.screenshot({ path: "/tmp/ihealth-fish-oil.png", fullPage: true });
await clickButtonContaining("鱼油有哪些形式？");
await pause(500);
await page.screenshot({ path: "/tmp/ihealth-fish-oil-forms.png", fullPage: true });
const screenshots = ["/tmp/ihealth-home.png", "/tmp/ihealth-foods.png", "/tmp/ihealth-food-categories.png", "/tmp/ihealth-salmon.png", "/tmp/ihealth-vitamin-c.png", "/tmp/ihealth-vitamin-c-effects.png", "/tmp/ihealth-fish-oil.png", "/tmp/ihealth-fish-oil-forms.png"];
console.log(JSON.stringify({ title: await page.title(), url: page.url(), h1: await page.$eval("h1", (node) => node.textContent), screenshots }));
await browser.close();
